---
platform: linux

image: docker:///cloudfoundry/inigo-ci

params:
  ROUTABLE_DOMAIN_SUFFIX: 10.244.0.34.xip.io

inputs:
  - name: vizzini
    path: gopath/src/code.cloudfoundry.org/diego-release/vizzini

run:
  path: gopath/src/code.cloudfoundry.org/diego-release/vizzini/scripts/ci/run-vizzini
